/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   handle_redirections.c                              :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: guphilip <guphilip@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/04/19 17:53:51 by guphilip          #+#    #+#             */
/*   Updated: 2025/04/22 17:20:25 by guphilip         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "minishell.h"

/// @brief Redirect STDIN from the specified input file
/// @param filename The name of the input file to open and use as STDIN
static void	redir_input(char *filename)
{
	int	fd;

	fd = open(filename, O_RDONLY);
	if (fd == -1)
	{
		perror("open input");
		exit(EXIT_FAILURE);
	}
	dup2(fd, STDIN_FILENO);
	close(fd);
}

/// @brief Redirect STDOUT to the specified output file (truncate mode)
/// @param filename The name of the output file to open and use as STDOUT
static void	redir_output(char *filename)
{
	int	fd;

	fd = open(filename, O_WRONLY | O_CREAT | O_TRUNC, 0644);
	if (fd == -1)
	{
		perror("open output");
		exit(EXIT_FAILURE);
	}
	dup2(fd, STDOUT_FILENO);
	close(fd);
}

/// @brief Redirect STDOUT using a temporary file generated by a heredoc
/// @param filename The heredoc delimiter to use when creating the input
static void	redir_append(char *filename)
{
	int	fd;

	fd = open(filename, O_WRONLY | O_CREAT | O_APPEND, 0644);
	if (fd == -1)
	{
		perror("open append");
		exit(EXIT_FAILURE);
	}
	dup2(fd, STDOUT_FILENO);
	close(fd);
}

/// @brief Redirect STDIN using a temporary file generated by a heredoc
/// @param delimiter The heredoc delimiter to use when creating the input
///					content
static void	redir_heredoc(char *delimiter)
{
	int	fd;

	fd = create_heredoc_fd(delimiter);
	if (fd == -1)
	{
		perror("heredoc");
		exit(EXIT_FAILURE);
	}
	dup2(fd, STDIN_FILENO);
	close(fd);
}

/// @brief Apply all redirections defined in a redirection list
/// @param redir Pointer to the redirection list to apply
void	apply_shell_redirections(t_redir *redir)
{
	while (redir)
	{
		if (redir->type == R_INPUT)
			redir_input(redir->filename);
		else if (redir->type == R_OUTPUT)
			redir_output(redir->filename);
		else if (redir->type == R_APPEND)
			redir_append(redir->filename);
		else if (redir->type == R_HEREDOC)
			redir_heredoc(redir->filename);
		redir = redir->next;
	}
}
